name: assets_cleaner
description: Scanning assets and remove unused file
version: 0.0.1
homepage: https://github.com/yusriltakeuchi/assets_cleaner.git

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  args: ^2.3.1
  path: ^1.8.0
  yaml: ^3.1.0
  logger: ^1.1.0

executables:
  assets_cleaner: assets_cleaner