name: assets_cleaner
description: A command-line tool wich helps you to clean your assets folder. It will remove all files that are not used in your project.
version: 0.0.2+7
homepage: https://github.com/yusriltakeuchi/assets_cleaner.git

environment:
  sdk: ">=2.19.6 <=3.0.10"

dependencies:
  args: ^2.3.1
  path: ^1.8.0
  yaml: ^3.1.0
  logger: ^1.1.0

platforms:
  linux:
  windows:
  macos:

screenshots:
  - description: "Assets Cleaner Screenshot"
    path: images/assets_cleaner.png

executables:
  assets_cleaner: assets_cleaner