name: assets_cleaner
description: A command-line tool wich helps you to clean your assets folder. It will remove all files that are not used in your project.
version: 0.1.3+9
homepage: https://github.com/yusriltakeuchi/assets_cleaner.git

environment:
  sdk: ">=2.19.6 <=3.6.10"

dependencies:
  args: ^2.5.0
  path: ^1.9.0
  yaml: ^3.1.2
  glob: ^2.1.2

platforms:
  linux:
  windows:
  macos:

screenshots:
  - description: "Assets Cleaner Screenshot"
    path: images/assets_cleaner.png

executables:
  assets_cleaner: assets_cleaner